// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * GetDepartments
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetDepartments": () => {
        return window.go.main.App.GetDepartments();
      },
      /**
       * Greet
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": () => {
        return window.go.main.App.Greet();
      },
      /**
       * Install
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Install": (arg1) => {
        return window.go.main.App.Install(arg1);
      },
      /**
       * Sysvars
       * @returns {Promise<string>}  - Go Type: string
       */
      "Sysvars": () => {
        return window.go.main.App.Sysvars();
      },
    },
  },

  "sys": {
    "Sys": {
      /**
       * All
       * @returns {Promise<Sys>}  - Go Type: *sys.Sys
       */
      "All": () => {
        return window.go.sys.Sys.All();
      },
      /**
       * Exec
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "Exec": (arg1) => {
        return window.go.sys.Sys.Exec(arg1);
      },
      /**
       * GetRemoteFile
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<void>} 
       */
      "GetRemoteFile": (arg1, arg2) => {
        return window.go.sys.Sys.GetRemoteFile(arg1, arg2);
      },
    },
  },

};
export default go;
