// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * Greet
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": () => {
        return window.go.main.App.Greet();
      },
      /**
       * Sysvars
       * @returns {Promise<string>}  - Go Type: string
       */
      "Sysvars": () => {
        return window.go.main.App.Sysvars();
      },
    },
  },

  "sys": {
    "Sys": {
      /**
       * All
       * @returns {Promise<Sys>}  - Go Type: *sys.Sys
       */
      "All": () => {
        return window.go.sys.Sys.All();
      },
    },
  },

};
export default go;
